/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TournamentUpdateEvent } from "./modules/tournaments/tournaments.types";
import { GenericTeam } from "./components.d";
export { TournamentUpdateEvent } from "./modules/tournaments/tournaments.types";
export { GenericTeam } from "./components.d";
export namespace Components {
    interface AppRoot {
    }
    interface GridBasket {
        "tournamentId": number | null;
    }
    interface GridDefault {
        "tournamentId": number | null;
    }
    interface MadInputNumber {
        "label"?: string;
        "max"?: number;
        /**
          * @default 0
         */
        "min"?: number | null;
        "placeholder": string;
        "readonly"?: boolean;
        "step"?: number;
        "value"?: number;
    }
    interface MadRoute {
        "component": string;
        "url": string;
    }
    interface MadScorerBasket {
        "max"?: number;
        "min"?: number;
        "readonly"?: boolean;
        "value"?: number;
    }
    interface MadScorerRugby {
        "max"?: number;
        "min"?: number;
        "readonly"?: boolean;
        "value"?: number;
    }
    interface MadTeamTile {
        "rank"?: number;
        "reverse": boolean | null;
        "team": GenericTeam | null;
    }
    interface PageConfig {
    }
    interface PageTournament {
        "tournamentId": number;
    }
    interface PageTournamentSelect {
    }
}
export interface GridBasketCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGridBasketElement;
}
export interface GridDefaultCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGridDefaultElement;
}
export interface MadInputNumberCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMadInputNumberElement;
}
export interface MadScorerBasketCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMadScorerBasketElement;
}
export interface MadScorerRugbyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMadScorerRugbyElement;
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLGridBasketElementEventMap {
        "gridTournamentChange": TournamentUpdateEvent;
    }
    interface HTMLGridBasketElement extends Components.GridBasket, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGridBasketElementEventMap>(type: K, listener: (this: HTMLGridBasketElement, ev: GridBasketCustomEvent<HTMLGridBasketElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGridBasketElementEventMap>(type: K, listener: (this: HTMLGridBasketElement, ev: GridBasketCustomEvent<HTMLGridBasketElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGridBasketElement: {
        prototype: HTMLGridBasketElement;
        new (): HTMLGridBasketElement;
    };
    interface HTMLGridDefaultElementEventMap {
        "gridTournamentChange": TournamentUpdateEvent;
    }
    interface HTMLGridDefaultElement extends Components.GridDefault, HTMLStencilElement {
        addEventListener<K extends keyof HTMLGridDefaultElementEventMap>(type: K, listener: (this: HTMLGridDefaultElement, ev: GridDefaultCustomEvent<HTMLGridDefaultElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLGridDefaultElementEventMap>(type: K, listener: (this: HTMLGridDefaultElement, ev: GridDefaultCustomEvent<HTMLGridDefaultElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLGridDefaultElement: {
        prototype: HTMLGridDefaultElement;
        new (): HTMLGridDefaultElement;
    };
    interface HTMLMadInputNumberElementEventMap {
        "madNumberChange": { value: string };
    }
    interface HTMLMadInputNumberElement extends Components.MadInputNumber, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMadInputNumberElementEventMap>(type: K, listener: (this: HTMLMadInputNumberElement, ev: MadInputNumberCustomEvent<HTMLMadInputNumberElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMadInputNumberElementEventMap>(type: K, listener: (this: HTMLMadInputNumberElement, ev: MadInputNumberCustomEvent<HTMLMadInputNumberElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMadInputNumberElement: {
        prototype: HTMLMadInputNumberElement;
        new (): HTMLMadInputNumberElement;
    };
    interface HTMLMadRouteElement extends Components.MadRoute, HTMLStencilElement {
    }
    var HTMLMadRouteElement: {
        prototype: HTMLMadRouteElement;
        new (): HTMLMadRouteElement;
    };
    interface HTMLMadScorerBasketElementEventMap {
        "madNumberChange": { value: string };
    }
    interface HTMLMadScorerBasketElement extends Components.MadScorerBasket, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMadScorerBasketElementEventMap>(type: K, listener: (this: HTMLMadScorerBasketElement, ev: MadScorerBasketCustomEvent<HTMLMadScorerBasketElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMadScorerBasketElementEventMap>(type: K, listener: (this: HTMLMadScorerBasketElement, ev: MadScorerBasketCustomEvent<HTMLMadScorerBasketElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMadScorerBasketElement: {
        prototype: HTMLMadScorerBasketElement;
        new (): HTMLMadScorerBasketElement;
    };
    interface HTMLMadScorerRugbyElementEventMap {
        "madNumberChange": { value: string };
    }
    interface HTMLMadScorerRugbyElement extends Components.MadScorerRugby, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMadScorerRugbyElementEventMap>(type: K, listener: (this: HTMLMadScorerRugbyElement, ev: MadScorerRugbyCustomEvent<HTMLMadScorerRugbyElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMadScorerRugbyElementEventMap>(type: K, listener: (this: HTMLMadScorerRugbyElement, ev: MadScorerRugbyCustomEvent<HTMLMadScorerRugbyElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMadScorerRugbyElement: {
        prototype: HTMLMadScorerRugbyElement;
        new (): HTMLMadScorerRugbyElement;
    };
    interface HTMLMadTeamTileElement extends Components.MadTeamTile, HTMLStencilElement {
    }
    var HTMLMadTeamTileElement: {
        prototype: HTMLMadTeamTileElement;
        new (): HTMLMadTeamTileElement;
    };
    interface HTMLPageConfigElement extends Components.PageConfig, HTMLStencilElement {
    }
    var HTMLPageConfigElement: {
        prototype: HTMLPageConfigElement;
        new (): HTMLPageConfigElement;
    };
    interface HTMLPageTournamentElement extends Components.PageTournament, HTMLStencilElement {
    }
    var HTMLPageTournamentElement: {
        prototype: HTMLPageTournamentElement;
        new (): HTMLPageTournamentElement;
    };
    interface HTMLPageTournamentSelectElement extends Components.PageTournamentSelect, HTMLStencilElement {
    }
    var HTMLPageTournamentSelectElement: {
        prototype: HTMLPageTournamentSelectElement;
        new (): HTMLPageTournamentSelectElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "grid-basket": HTMLGridBasketElement;
        "grid-default": HTMLGridDefaultElement;
        "mad-input-number": HTMLMadInputNumberElement;
        "mad-route": HTMLMadRouteElement;
        "mad-scorer-basket": HTMLMadScorerBasketElement;
        "mad-scorer-rugby": HTMLMadScorerRugbyElement;
        "mad-team-tile": HTMLMadTeamTileElement;
        "page-config": HTMLPageConfigElement;
        "page-tournament": HTMLPageTournamentElement;
        "page-tournament-select": HTMLPageTournamentSelectElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface GridBasket {
        "onGridTournamentChange"?: (event: GridBasketCustomEvent<TournamentUpdateEvent>) => void;
        "tournamentId"?: number | null;
    }
    interface GridDefault {
        "onGridTournamentChange"?: (event: GridDefaultCustomEvent<TournamentUpdateEvent>) => void;
        "tournamentId"?: number | null;
    }
    interface MadInputNumber {
        "label"?: string;
        "max"?: number;
        /**
          * @default 0
         */
        "min"?: number | null;
        "onMadNumberChange"?: (event: MadInputNumberCustomEvent<{ value: string }>) => void;
        "placeholder"?: string;
        "readonly"?: boolean;
        "step"?: number;
        "value"?: number;
    }
    interface MadRoute {
        "component"?: string;
        "url"?: string;
    }
    interface MadScorerBasket {
        "max"?: number;
        "min"?: number;
        "onMadNumberChange"?: (event: MadScorerBasketCustomEvent<{ value: string }>) => void;
        "readonly"?: boolean;
        "value"?: number;
    }
    interface MadScorerRugby {
        "max"?: number;
        "min"?: number;
        "onMadNumberChange"?: (event: MadScorerRugbyCustomEvent<{ value: string }>) => void;
        "readonly"?: boolean;
        "value"?: number;
    }
    interface MadTeamTile {
        "rank"?: number;
        "reverse"?: boolean | null;
        "team"?: GenericTeam | null;
    }
    interface PageConfig {
    }
    interface PageTournament {
        "tournamentId"?: number;
    }
    interface PageTournamentSelect {
    }

    interface GridBasketAttributes {
        "tournamentId": number | null;
    }
    interface GridDefaultAttributes {
        "tournamentId": number | null;
    }
    interface MadInputNumberAttributes {
        "placeholder": string;
        "label": string;
        "min": number | null;
        "max": number;
        "step": number;
        "value": number;
        "readonly": boolean;
    }
    interface MadRouteAttributes {
        "url": string;
        "component": string;
    }
    interface MadScorerBasketAttributes {
        "min": number;
        "max": number;
        "value": number;
        "readonly": boolean;
    }
    interface MadScorerRugbyAttributes {
        "min": number;
        "max": number;
        "value": number;
        "readonly": boolean;
    }
    interface MadTeamTileAttributes {
        "team": string;
        "reverse": boolean | null;
        "rank": number;
    }
    interface PageTournamentAttributes {
        "tournamentId": number;
    }

    interface IntrinsicElements {
        "app-root": AppRoot;
        "grid-basket": Omit<GridBasket, keyof GridBasketAttributes> & { [K in keyof GridBasket & keyof GridBasketAttributes]?: GridBasket[K] } & { [K in keyof GridBasket & keyof GridBasketAttributes as `attr:${K}`]?: GridBasketAttributes[K] } & { [K in keyof GridBasket & keyof GridBasketAttributes as `prop:${K}`]?: GridBasket[K] };
        "grid-default": Omit<GridDefault, keyof GridDefaultAttributes> & { [K in keyof GridDefault & keyof GridDefaultAttributes]?: GridDefault[K] } & { [K in keyof GridDefault & keyof GridDefaultAttributes as `attr:${K}`]?: GridDefaultAttributes[K] } & { [K in keyof GridDefault & keyof GridDefaultAttributes as `prop:${K}`]?: GridDefault[K] };
        "mad-input-number": Omit<MadInputNumber, keyof MadInputNumberAttributes> & { [K in keyof MadInputNumber & keyof MadInputNumberAttributes]?: MadInputNumber[K] } & { [K in keyof MadInputNumber & keyof MadInputNumberAttributes as `attr:${K}`]?: MadInputNumberAttributes[K] } & { [K in keyof MadInputNumber & keyof MadInputNumberAttributes as `prop:${K}`]?: MadInputNumber[K] };
        "mad-route": Omit<MadRoute, keyof MadRouteAttributes> & { [K in keyof MadRoute & keyof MadRouteAttributes]?: MadRoute[K] } & { [K in keyof MadRoute & keyof MadRouteAttributes as `attr:${K}`]?: MadRouteAttributes[K] } & { [K in keyof MadRoute & keyof MadRouteAttributes as `prop:${K}`]?: MadRoute[K] };
        "mad-scorer-basket": Omit<MadScorerBasket, keyof MadScorerBasketAttributes> & { [K in keyof MadScorerBasket & keyof MadScorerBasketAttributes]?: MadScorerBasket[K] } & { [K in keyof MadScorerBasket & keyof MadScorerBasketAttributes as `attr:${K}`]?: MadScorerBasketAttributes[K] } & { [K in keyof MadScorerBasket & keyof MadScorerBasketAttributes as `prop:${K}`]?: MadScorerBasket[K] };
        "mad-scorer-rugby": Omit<MadScorerRugby, keyof MadScorerRugbyAttributes> & { [K in keyof MadScorerRugby & keyof MadScorerRugbyAttributes]?: MadScorerRugby[K] } & { [K in keyof MadScorerRugby & keyof MadScorerRugbyAttributes as `attr:${K}`]?: MadScorerRugbyAttributes[K] } & { [K in keyof MadScorerRugby & keyof MadScorerRugbyAttributes as `prop:${K}`]?: MadScorerRugby[K] };
        "mad-team-tile": Omit<MadTeamTile, keyof MadTeamTileAttributes> & { [K in keyof MadTeamTile & keyof MadTeamTileAttributes]?: MadTeamTile[K] } & { [K in keyof MadTeamTile & keyof MadTeamTileAttributes as `attr:${K}`]?: MadTeamTileAttributes[K] } & { [K in keyof MadTeamTile & keyof MadTeamTileAttributes as `prop:${K}`]?: MadTeamTile[K] };
        "page-config": PageConfig;
        "page-tournament": Omit<PageTournament, keyof PageTournamentAttributes> & { [K in keyof PageTournament & keyof PageTournamentAttributes]?: PageTournament[K] } & { [K in keyof PageTournament & keyof PageTournamentAttributes as `attr:${K}`]?: PageTournamentAttributes[K] } & { [K in keyof PageTournament & keyof PageTournamentAttributes as `prop:${K}`]?: PageTournament[K] };
        "page-tournament-select": PageTournamentSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.IntrinsicElements["app-root"] & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "grid-basket": LocalJSX.IntrinsicElements["grid-basket"] & JSXBase.HTMLAttributes<HTMLGridBasketElement>;
            "grid-default": LocalJSX.IntrinsicElements["grid-default"] & JSXBase.HTMLAttributes<HTMLGridDefaultElement>;
            "mad-input-number": LocalJSX.IntrinsicElements["mad-input-number"] & JSXBase.HTMLAttributes<HTMLMadInputNumberElement>;
            "mad-route": LocalJSX.IntrinsicElements["mad-route"] & JSXBase.HTMLAttributes<HTMLMadRouteElement>;
            "mad-scorer-basket": LocalJSX.IntrinsicElements["mad-scorer-basket"] & JSXBase.HTMLAttributes<HTMLMadScorerBasketElement>;
            "mad-scorer-rugby": LocalJSX.IntrinsicElements["mad-scorer-rugby"] & JSXBase.HTMLAttributes<HTMLMadScorerRugbyElement>;
            "mad-team-tile": LocalJSX.IntrinsicElements["mad-team-tile"] & JSXBase.HTMLAttributes<HTMLMadTeamTileElement>;
            "page-config": LocalJSX.IntrinsicElements["page-config"] & JSXBase.HTMLAttributes<HTMLPageConfigElement>;
            "page-tournament": LocalJSX.IntrinsicElements["page-tournament"] & JSXBase.HTMLAttributes<HTMLPageTournamentElement>;
            "page-tournament-select": LocalJSX.IntrinsicElements["page-tournament-select"] & JSXBase.HTMLAttributes<HTMLPageTournamentSelectElement>;
        }
    }
}
